"""Database operations and models."""

from .client import get_client, get_supabase_client
from .operations import (
    get_vintage,
    get_vintage_data,
    get_vintage_data_for_config,
    get_latest_vintage_id,
    create_vintage,
    update_vintage_status,
    ensure_vintage_and_job,
    finalize_ingestion_job,
    delete_old_vintages,
    insert_observations_from_dataframe,
    get_statistics_metadata,
    get_active_items_for_statistic,
    update_statistics_metadata_status,
    list_dfm_selected_statistics,
    get_series_metadata_bulk,
    save_forecast,
    generate_series_id,
    get_series,
    upsert_series,
    save_model_config,
    check_series_exists,
)
from .helpers import resolve_config_name
from .models import SeriesModel

__all__ = [
    'get_client',
    'get_supabase_client',
    'get_vintage',
    'get_vintage_data',
    'get_vintage_data_for_config',
    'get_latest_vintage_id',
    'create_vintage',
    'update_vintage_status',
    'ensure_vintage_and_job',
    'finalize_ingestion_job',
    'delete_old_vintages',
    'insert_observations_from_dataframe',
    'get_statistics_metadata',
    'get_active_items_for_statistic',
    'update_statistics_metadata_status',
    'list_dfm_selected_statistics',
    'get_series_metadata_bulk',
    'save_forecast',
    'generate_series_id',
    'get_series',
    'upsert_series',
    'save_model_config',
    'check_series_exists',
    'resolve_config_name',
    'SeriesModel',
]
