name: ddfm
target_series:
- KOEQUIPTE
encoder_layers:
- 64
- 32
num_factors: 3
activation: relu
use_batch_norm: true
learning_rate: 0.005
n_mc_samples: 10
window_size: 100
max_epoch: 50
tolerance: 0.0005
disp: 10
seed: null
use_idiosyncratic: true
min_obs_idio: 5
lags_input: 0
target_scaler: standard
