name: ddfm
target_series:
- KOEQUIPTE
encoder_layers:
- 32
- 16
num_factors: 5
activation: relu
use_batch_norm: true
learning_rate: 0.0005
n_mc_samples: 10
window_size: 100
max_epoch: 50
tolerance: 0.0005
disp: 10
seed: null
use_idiosyncratic: true
min_obs_idio: 5
lags_input: 0
scaler: standard
interpolation_method: linear
interpolation_limit: 10
interpolation_limit_direction: both