name: dfm
ar_lag: 4
ar_order: 4
threshold: 1.0e-05
max_iter: 5000
clip_ar_coefficients: true
ar_clip_min: -0.99
ar_clip_max: 0.99
use_regularization: true
regularization_scale: 1.0e-05
augment_idio: false
augment_idio_slow: false
idio_rho0: 0.1
idio_min_var: 1.0e-08
clock: w
mixed_freq: true
scaler: robust
blocks:
  Block_Global:
    num_factors: 3
    series:
    - A001
    - GSCITOT
    - KOBDY10
    - KOBFDSAAF
    - KOBFINAAF
    - KOBFPRAAF
    - KOBFXSAAF
    - KOBSESI.R
    - KOBSIBAPR
    - KOBSIBCEQ
    - KOBSIBCOQ
    - KOBSIBMAR
    - KOBSIBMPR
    - KOBSIBNER
    - KOBSIBNMR
    - KOBSIBNPR
    - KOBSIEMAR
    - KOBSIFAPR
    - KOBSIHAPR
    - KOBSIIMER
    - KOBSIIMPR
    - KOBSIRMER
    - KOBSISAPR
    - KOBSIXMER
    - KOBSIYAPR
    - KOBUSINVR
    - KOCBNG3
    - KOCNFBUSR
    - KOCNFCONR
    - KOCOBUSIR
    - KOCONPMTH
    - KOCONPRCF
    - KOCONSTRP
    - KOCPCOREF
    - KOCPEXFEF
    - KOCREU..A
    - KOCSECDMR
    - KOCSECEMR
    - KOCSEMEMR
    - KOCSEOHDR
    - KOCSEOHSR
    - KOCSHHEMR
    - KOCSHHLMR
    - KOCSMTTOA
    - KOCSPHIMR
    - KOCSPSPMR
    - KOCYLEADR
    - KODBLNEQA
    - KODBLNHSA
    - KODBLNSPA
    - KOEMPCONF
    - KOEMPMANF
    - KOEMPTOTO
    - KOEMPWREP
    - KOEQUIMAE
    - KOEQUIPTE
    - KOEQUITTE
    - KOEXCHINA
    - KOEXPGDSA
    - KOEXPMOVH
    - KOEXPPRCF
    - KOEXPSCOH
    - KOHWRWEMP
    - KOIMPCONA
    - KOIMPGDDA
    - KOIMPGDSA
    - KOIMPPRCF
    - KOIPALL.G
    - KOIPCHXPG
    - KOIPCOMPG
    - KOIPMIMAG
    - KOIPVECHG
    - KOIPXBSBG
    - KOLRLTCO
    - KOLRLTHH
    - KOMPCAPGG
    - KOMPCONDG
    - KOMPCONGG
    - KOMPCONNG
    - KOMPRI30G
    - KOMSCAPGG
    - KOMSCONGG
    - KONETTRDF
    - KONEWCONA
    - KOPICAPGG
    - KOPICONGG
    - KOPIMANUG
    - KOPOPACTE
    - KOPPSRM.F
    - KOPROPRCF
    - KOPSMANUG
    - KORCNST
    - KORCOMP
    - KORELEC
    - KORFBEV
    - KORMACH
    - KORMCMP
    - KOROCOINF
    - KORSERV
    - KORWHLS
    - KOSIAHOTE
    - KOSIAI..E
    - KOSIARRLE
    - KOSIATRNE
    - KOSIAWRTE
    - KOSSBFMBE
    - KOUN%TOTQ
    - KOVALCONA
    - KOWRCCNSE
    - KOWRCDURE
    - KOWRCNODE
    - KOWRCSEME
    - USSKORW
  Block_Consumption:
    num_factors: 2
    series:
    - KOBSIBNMR
    - KOBSIEMAR
    - KOCNFBUSR
    - KOCNFCONR
    - KOCONPRCF
    - KOCPCOREF
    - KOCPEXFEF
    - KOCREU..A
    - KOCSECDMR
    - KOCSECEMR
    - KOCSEMEMR
    - KOCSEOHDR
    - KOCSEOHSR
    - KOCSHHEMR
    - KOCSHHLMR
    - KOCSMTTOA
    - KOCSPHIMR
    - KOCSPSPMR
    - KODBLNHSA
    - KOEMPWREP
    - KOIMPCONA
    - KOMPCONGG
    - KOMPCONNG
    - KOPICONGG
    - KOSIAHOTE
    - KOSIAI..E
    - KOSIAWRTE
    - KOWRCCNSE
    - KOWRCDURE
    - KOWRCNODE
    - KOWRCSEME
  Block_Investment:
    num_factors: 2
    series:
    - KOBFINAAF
    - KOBSIIMER
    - KOBSIIMPR
    - KOBUSINVR
    - KOCONPMTH
    - KOCONSTRP
    - KODBLNEQA
    - KOEMPCONF
    - KOEQUIMAE
    - KOEQUIPTE
    - KOEQUITTE
    - KOIMPGDDA
    - KOLRLTCO
    - KOMPCAPGG
    - KOMPCONDG
    - KOMPRI30G
    - KOMSCAPGG
    - KONEWCONA
    - KOPICAPGG
    - KOVALCONA
  Block_Export:
    num_factors: 1
    series:
    - KOBSIXMER
    - KOEXCHINA
    - KOEXPGDSA
    - KOEXPMOVH
    - KOEXPSCOH
    - KONETTRDF
  Block_Nominal:
    num_factors: 1
    series:
    - KOEXPGDSA
    - KOIMPGDSA
    - KOIMPPRCF
    - KODBLNHSA
    - KODBLNEQA
    - KODBLNSPA
    - KOIMPCONA
    - KOIMPGDDA
    - KOLRLTHH
    - KONEWCONA
    - KOPPSRM.F
    - KOPROPRCF
    - KOVALCONA
  Block_Labor:
    num_factors: 1
    series:
    - KOBSIHAPR
    - KOCSEMEMR
    - KOEMPTOTO
    - KOHWRWEMP
    - KOPOPACTE
    - KOUN%TOTQ
  Block_RiskApp:
    num_factors: 1
    series:
    - KOBDY10
    - KOCBNG3
    - KOLRLTHH
    - KORCOMP
    - USSKORW
frequency:
  w:
  - A001
  - GSCITOT
  - KOBDY10
  - KOCBNG3
  - KORCNST
  - KORCOMP
  - KORELEC
  - KORFBEV
  - KORMACH
  - KORMCMP
  - KORSERV
  - KORWHLS
  - USSKORW
  m:
  - KOBFDSAAF
  - KOBFINAAF
  - KOBFPRAAF
  - KOBFXSAAF
  - KOBSESI.R
  - KOBSIBAPR
  - KOBSIBCEQ
  - KOBSIBCOQ
  - KOBSIBMAR
  - KOBSIBMPR
  - KOBSIBNER
  - KOBSIBNMR
  - KOBSIBNPR
  - KOBSIEMAR
  - KOBSIFAPR
  - KOBSIHAPR
  - KOBSIIMER
  - KOBSIIMPR
  - KOBSIRMER
  - KOBSISAPR
  - KOBSIXMER
  - KOBSIYAPR
  - KOBUSINVR
  - KOCNFBUSR
  - KOCNFCONR
  - KOCOBUSIR
  - KOCONPMTH
  - KOCONPRCF
  - KOCONSTRP
  - KOCPCOREF
  - KOCPEXFEF
  - KOCREU..A
  - KOCSECDMR
  - KOCSECEMR
  - KOCSEMEMR
  - KOCSEOHDR
  - KOCSEOHSR
  - KOCSHHEMR
  - KOCSHHLMR
  - KOCSMTTOA
  - KOCSPHIMR
  - KOCSPSPMR
  - KOCYLEADR
  - KODBLNEQA
  - KODBLNHSA
  - KODBLNSPA
  - KOEMPCONF
  - KOEMPMANF
  - KOEMPTOTO
  - KOEMPWREP
  - KOEQUIMAE
  - KOEQUIPTE
  - KOEQUITTE
  - KOEXCHINA
  - KOEXPGDSA
  - KOEXPMOVH
  - KOEXPPRCF
  - KOEXPSCOH
  - KOHWRWEMP
  - KOIMPCONA
  - KOIMPGDDA
  - KOIMPGDSA
  - KOIMPPRCF
  - KOIPALL.G
  - KOIPCHXPG
  - KOIPCOMPG
  - KOIPMIMAG
  - KOIPVECHG
  - KOIPXBSBG
  - KOLRLTCO
  - KOLRLTHH
  - KOMPCAPGG
  - KOMPCONDG
  - KOMPCONGG
  - KOMPCONNG
  - KOMPRI30G
  - KOMSCAPGG
  - KOMSCONGG
  - KONETTRDF
  - KONEWCONA
  - KOPICAPGG
  - KOPICONGG
  - KOPIMANUG
  - KOPOPACTE
  - KOPPSRM.F
  - KOPROPRCF
  - KOPSMANUG
  - KOROCOINF
  - KOSIAHOTE
  - KOSIAI..E
  - KOSIARRLE
  - KOSIATRNE
  - KOSIAWRTE
  - KOSSBFMBE
  - KOUN%TOTQ
  - KOVALCONA
  - KOWRCCNSE
  - KOWRCDURE
  - KOWRCNODE
  - KOWRCSEME
target_series:
- KOEQUIPTE
